name: Newifi3-Build

on:
  #schedule:
    #- cron: 0 10 * * 0
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    #if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo msodbcsql17 msodbcsql/ACCEPT_EULA boolean true | sudo debconf-set-selections
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man libc6-dev-i386 \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth 1 https://github.com/xumng123/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: NEWIFI3
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config

        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_USB.*=.*/CONFIG_FIRMWARE_ENABLE_USB=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_UFSD.*=.*/CONFIG_FIRMWARE_ENABLE_UFSD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_FAT.*=.*/CONFIG_FIRMWARE_ENABLE_FAT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_EXFAT.*=.*/CONFIG_FIRMWARE_ENABLE_EXFAT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_EXT2.*=.*/CONFIG_FIRMWARE_ENABLE_EXT2=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_EXT3.*=.*/CONFIG_FIRMWARE_ENABLE_EXT3=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_EXT4.*=.*/CONFIG_FIRMWARE_ENABLE_EXT4=n/g' .config		
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_FUSE.*=.*/CONFIG_FIRMWARE_ENABLE_FUSE=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_UVC.*=.*/CONFIG_FIRMWARE_INCLUDE_UVC=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SERIAL.*=.*/CONFIG_FIRMWARE_INCLUDE_SERIAL=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_AUDIO.*=.*/CONFIG_FIRMWARE_INCLUDE_AUDIO=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_LPRD.*=.*/CONFIG_FIRMWARE_INCLUDE_LPRD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_U2EC.*=.*/CONFIG_FIRMWARE_INCLUDE_U2EC=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_TCPDUMP.*=.*/CONFIG_FIRMWARE_INCLUDE_TCPDUMP=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_HDPARM.*=.*/CONFIG_FIRMWARE_INCLUDE_HDPARM=n/g' .config		
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_PARTED.*=.*/CONFIG_FIRMWARE_INCLUDE_PARTED=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SMBD=.*/CONFIG_FIRMWARE_INCLUDE_SMBD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SMBD36.*=.*/CONFIG_FIRMWARE_INCLUDE_SMBD36=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_FTPD.*=.*/CONFIG_FIRMWARE_INCLUDE_FTPD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_EAP_PEAP.*=.*/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_XUPNPD.*=.*/CONFIG_FIRMWARE_INCLUDE_XUPNPD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW.*=.*/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_ARIA=.*/CONFIG_FIRMWARE_INCLUDE_ARIA=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL.*=.*/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT.*=.*/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_DOGCOM.*=.*/CONFIG_FIRMWARE_INCLUDE_DOGCOM=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_MINIEAP.*=.*/CONFIG_FIRMWARE_INCLUDE_MINIEAP=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT.*=.*/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_NAPT66.*=.*/CONFIG_FIRMWARE_INCLUDE_NAPT66=y/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS.*=.*/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SSSERVER.*=.*/CONFIG_FIRMWARE_INCLUDE_SSSERVER=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER.*=.*/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT.*=.*/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD.*=.*/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER.*=.*/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_VLMCSD.*=.*/CONFIG_FIRMWARE_INCLUDE_VLMCSD=y/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_TTYD.*=.*/CONFIG_FIRMWARE_INCLUDE_TTYD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_MTR.*=.*/CONFIG_FIRMWARE_INCLUDE_MTR=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SOCAT.*=.*/CONFIG_FIRMWARE_INCLUDE_SOCAT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SRELAY.*=.*/CONFIG_FIRMWARE_INCLUDE_SRELAY=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_MENTOHUST.*=.*/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SSOBFS.*=.*/CONFIG_FIRMWARE_INCLUDE_SSOBFS=y/g' .config
        #sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_V2RAY.*=.*/CONFIG_FIRMWARE_INCLUDE_V2RAY=y/g' .config
        #sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SMARTDNS.*=.*/CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y/g' .config
        #sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_ZEROTIER.*=.*/CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y/g' .config
        #sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_ALIDDNS.*=.*/CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y/g' .config
        #sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_ADBYBY.*=.*/CONFIG_FIRMWARE_INCLUDE_ADBYBY=y/g' .config
        #sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_KOOLPROXY.*=.*/CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=y/g' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/a CONFIG_FIRMWARE_INCLUDE_ADBYBY=n' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/a CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/a CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/a CONFIG_FIRMWARE_INCLUDE_V2RAY=y' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/a CONFIG_FIRMWARE_INCLUDE_TROJAN=y' .config
        
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/

    - name: Upload packages
      uses: actions/upload-artifact@main
      if: always()
      with:
        name: Padavan-Newifi3
        path: /opt/images

    - name: Get current time
      uses: iboosting/get-current-time@master
      id: current-time
      with:
        format: YYYYMMDDHHSS
        utcOffset: "+08:00"

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /opt/images/*.trx
        tag: ${{ steps.current-time.outputs.formattedTime }}
        file_glob: true
        overwrite: true
